Add nvim and Post Install Scripts

diff --git a/gadi b/gadi
--- a/gadi
+++ b/gadi
@@ -19,6 +19,9 @@ function install_components() {
     components=$1
 
     for component in "${components[@]}"; do
+        package="$currentdir/components/$component/package.txt"
+        postinstall="$currentdir/components/$component/postinstall.sh"
+
         while read -r line; do
             if [ -z "$line" ]; then
                 continue
@@ -35,9 +38,16 @@ function install_components() {
                 read -r url
                 read -r -a bins
 
-                $currentdir/tbzei $mountpoint pains $pkgname $url $bins
+                $currentdir/tbzei $mountpoint pains $pkgname $url $bins \
+                    || $(echo "  - $pkgname failed to install." && exit 1)
             fi
-        done < "$currentdir/components/$component.txt"
+        done < $package
+
+        if [[ -f $postinstall ]]; then
+            bash $postinstall $($currentdir/tbzei $mountpoint pkgdir $pkgname) \
+                && echo "  - [s] postinstall" \
+                || echo "  - $package postinstall.sh failed."
+        fi
     done
 }
 
